name: Automate update readme

on:
  schedule:
    - cron:  '0 0 */2 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependency
      run: npm install cheerio request --save
    - name: Update readme
      run: node main.js
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto update README.md
